export const CommonErrorCode = {
  VALIDATION_ERROR: 'COMMON.VALIDATION_ERROR',
  NOT_FOUND: 'COMMON.NOT_FOUND',
  UNAUTHORIZED: 'COMMON.UNAUTHORIZED',
  CONFLICT: 'COMMON.CONFLICT',
  FORBIDDEN: 'COMMON.FORBIDDEN',
} as const;
