export const IamErrorCode = {
  INVALID_CREDENTIALS: 'IAM.INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'IAM.TOKEN_EXPIRED',
  TOKEN_INVALID: 'IAM.TOKEN_INVALID',
  INVALID_ACCOUNT: 'IAM.INVALID_ACCOUNT',
  INVALID_USER: 'IAM.INVALID_USER',
} as const;
